# https://stackoverflow.com/questions/59522052/gcp-cloudbuild-yaml-creates-workspace-tests-but-need-workspace-my-app-tests

# Each step specified in the cloudbuild.yaml is a separate, ephemeral run of a docker image
steps:

  # Step 0 - Create the environment
  #   The /workspace/ directory is preserved between runs. One way to carry python packages
  #   forward is to use a virtualenv housed in /workspace/
- name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: '/bin/bash'
  args:
    [
      '-c',
      'python3 -m virtualenv /workspace/venv'
    ]

  # Step 1 - Clone the GitHub repo
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'venv'
  args:
    [
      'clone',
      '--recurse-submodules',
      'https://github.com/GDBSD/gcp-cicd-workflow'
    ]