# https://stackoverflow.com/questions/59522052/gcp-cloudbuild-yaml-creates-workspace-tests-but-need-workspace-my-app-tests

steps:

  # Step 0 - Install Python 3
  # Cloud Build automatically substitutes $PROJECT_ID for the GCP Project ID
- name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: '/bin/bash'
  args:
    [
      '-c',
      'python3 -m venv /workspace/gcp-cicd'
    ]

  # Step 1 - Install the dependencies
  # Installs any dependencies listed in the project's requirements.txt.
- name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
  entrypoint: 'gcp-cicd/bin/pip'
  args:
    [
      'install',
      '-V',
      '-r',
      'requirements.txt'
    ]

  # Step 2 - Clone the GitHub repo
- name: 'gcr.io/cloud-builders/git'
  args:
    [
      'clone',
      '--recurse-submodules',
      'https://github.com/GDBSD/gcp-cicd-workflow'
    ]
  dir: 'gcp-cicd-workflow'
