# This Dockerfile is used to build a custom cloud builder
# It pulls the public Python 3 image from Dockerhub (https://hub.docker.com/_/python)

FROM python:3

RUN apt-get update && apt-get install -y python3-pip

RUN pip install virtualenv
